name: release

on:
  release:
    types:
      - "published"

jobs:
  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyprobeplus
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Update Version
        run: |
          filepath="pyprobeplus/__init__.py"
          new_version_string="__version__ = \"${{ github.event.release.tag_name }}\""
          sed -i "s/^__version__ = .*$/$new_version_string/" "$filepath"
      - uses: extractions/setup-just@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build package
        run: just install build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
